"""empty message

Revision ID: 1e23921f7c35
Revises: 
Create Date: 2020-06-08 20:01:05.904737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e23921f7c35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actor', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('actor', 'gender',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('actor', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('movie_id', 'castings', type_='foreignkey')
    op.drop_constraint('actor_id', 'castings', type_='foreignkey')
    op.create_foreign_key(None, 'castings', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'castings', 'actor', ['actor_id'], ['id'])
    op.alter_column('movie', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('movie', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('movie', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'castings', type_='foreignkey')
    op.drop_constraint(None, 'castings', type_='foreignkey')
    op.create_foreign_key('actor_id', 'castings', 'actor', ['actor_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('movie_id', 'castings', 'movie', ['movie_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('actor', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('actor', 'gender',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('actor', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
